apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weather-api
  description: A simple weather API to manage city weather data
  tags:
    - api
    - weather
  annotations:
    backstage.io/managed-by: weather-team
spec:
  type: service
  lifecycle: production
  owner: weather-team
  links:
    - url: http://localhost:5000/api/weather
      title: Weather API
      rel: self
