apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-api
  links:
    - url: http://localhost:5000/api-docs/#/default/get_weather
      title: My Dashboard
  description: A simple weather API to manage city weather data
  tags:
    - anb
    - fisal7003
spec:
  type: openapi
  lifecycle: production
  owner: fisal7003
  definition:
    $text: https://github.com/iiethear0/Soap-server/blob/main/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: middleware
spec:
  type: openapi
  lifecycle: production
  owner: Faisal
  system: swagger
  providesApis: [weather-api]
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: swagger
spec:
  owner: fisal7003
