apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-api
  description: Faisal ....
spec:
  type: openapi
  lifecycle: production
  owner: weather-team
  definitions:
    swagger:
      url: http://localhost:5000/api-docs
