apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-api
  description: A simple weather API to manage city weather data
  tags:
    - anb
    - swagger
spec:
  type: openapi
  lifecycle: production
  owner: Faisal
  definition:
    $text: https://github.com/iiethear0/Soap-server/blob/main/openapi.yaml
