apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-api
  description: A simple weather API to manage city weather data
  tags:
    - anb
    - faisal
spec:
  type: openapi
  lifecycle: production
  owner: Faisal
  definition:
    $text: https://raw.githubusercontent.com/iiethear0/Soap-server/main/openapi.yaml
